### ISSUE TITLE
Cannot install requirements

### ISSUE THREAD

**Issue by ysimonson** [diogojc/heroku-buildpack-python-opencv-scipy#3]
I got the following error on push using this buildpack:

```
remote: -----> Found requirements.txt, installing dependencies using pip
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/bin/pip", line 7, in <module>
remote:     from pip import main
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/__init__.py", line 10, in <module>
remote:     from pip.util import get_installed_distributions, get_prog
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/util.py", line 18, in <module>
remote:     from pip._vendor.distlib import version
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_vendor/distlib/version.py", line 14, in <module>
remote:     from .compat import string_types
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_vendor/distlib/compat.py", line 31, in <module
remote:     from urllib2 import (Request, urlopen, URLError, HTTPError,
remote: ImportError: cannot import name HTTPSHandler
```

**Comment by juliomalegria** [comment]
Had a similar problem here. Thanks @diogojc, you're a lifesaver!

**Comment by juliomalegria** [comment]
Is this buildpack ever going to be supported in `cedar-14`?

```
remote:  !   Cedar-10 will reach end-of-life on November 4th, 2015.
remote:  !   Upgrade to Cedar-14 at your earliest convenience.
remote:  !   For more information, check out the following Dev Center article:
remote:  !   https://devcenter.heroku.com/articles/cedar-14-migration
```

**Comment by diogojc** [comment]
Hi Julio.

Yes, I'm currently vendoring these libraries for cedar-14 so I can include them in the buildpack.

I'm using docker with the cedar-14 base image to vendor everything that will eventually be gzipped and deployed using the buildpack.

Compiling opencv with the python bindings is proving harder then I thought. You can check the cedar-14 branch for progress.

**Comment by juliomalegria** [comment]
Awesome @diogojc!

**Comment by juliomalegria** [comment]
@diogojc Any news related to the `cedar-14` branch?

**Comment by diogojc** [comment]
@juliomalegria The latest commit of the branch should give you a fully functional environment of opencv, python, numpy and matplotlib.

I haven't managed to get scipy running though, but if you don't need that you should be able to use the buildpack already. Give it a spin in Heroku.
