### ISSUE TITLE
Install in a regular server

### ISSUE THREAD

**Issue by juliomalegria** [diogojc/heroku-buildpack-python-opencv-scipy#4]
Hi @diogojc,

Thanks for this buildpack! I've used it in a couple of heroku dynos and it works wonders!

Recently I adquired the smallest DigitalOcean instance (512MB memory) and wanted to install OpenCV there, but apparently you need more memory than that to compile it (it fails all the time with Out Of Memory).

So I was reading your `compile` file and I thought that maybe I could use the [env file](https://github.com/diogojc/heroku-buildpack-python-opencv-scipy/blob/master/bin/compile#L75) you use there and follow the same process to install OpenCV in a regular server. Do you think that would be possible? Could you give me some guidelines to how to do that?

**Comment by diogojc** [comment]
Buildpacks are sort of an Heroku thing.

In the cedar-14 branch you can see a Dockerfile with all the steps needed to create a container with all the libraries of this buildpack.

If you can run a docker daemon on that Digital Ocean machine instance you should be able to run the Dockerfile and eventually have the same end result.
