### ISSUE TITLE
opencv version issue

### ISSUE THREAD

**Issue by thaiat** [diogojc/heroku-buildpack-python-opencv-scipy#6]
Hi there,

I installed your buildpack for cedar14
When i run the following command:
```bash
heroku run python
>>> import cv2
>>> cv2.__version__
```
i  get `'2.4.10'`

your readme is saying it should be opencv 3...

**Comment by prodicus** [comment]
@thaiat I am getting a `pip` error. How did you configure the buildpack for you app?

**Comment by mhauss** [comment]
Yeah pip doesn't install opencv. There are git repos that make custom build
configurations for heroku, but none of them worked for me. So I never got
it to work.

You either have to get one of those working, or make your own custom build
pack (by compiling binaries on a virtual machine).

**Comment by prodicus** [comment]
@mhauss I am trying to deploy this app for [https://github.com/ytamura/thorn-hackathon.git](https://github.com/ytamura/thorn-hackathon.git) by setting the buildpack by doing a `heroku config:set BUILDPACK_URL=git://github.com/Azure-Vani/heroku-buildpack-opencv3.git`

I am getting the following error

```
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 602 bytes | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python + OpenCV + Numpy + Scipy app detected
remote: -----> Generating environment
remote:        Unpacking...
remote: -----> Found requirements.txt, installing dependencies using pip
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/bin/pip", line 7, in <module>
remote:     from pip import main
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/__init__.py", line 10, in <module>
remote:     from pip.util import get_installed_distributions, get_prog
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/util.py", line 18, in <module>
remote:     from pip._vendor.distlib import version
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_vendor/distlib/version.py", line 14, in <module>
remote:     from .compat import string_types
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_vendor/distlib/compat.py", line 31, in <module>
remote:     from urllib2 import (Request, urlopen, URLError, HTTPError,
remote: ImportError: cannot import name HTTPSHandler
remote: -----> Creating environment variables.
remote: -----> Buildpack installed.
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing...
remote:        Done: 160.8M
remote: -----> Launching...
remote:        Released v13
remote:        https://thorn.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/thorn.git
 + e3d4f7b...a143ca1 master -> master (forced update)
```

Any help on that?

**Comment by mhauss** [comment]
Nope

**Comment by diogojc** [comment]
Hey guys.

This buildpack only worked for cedar stack v13.

I tried to create binaries compatible with cedar stack v14 (see [this branch](https://github.com/diogojc/heroku-buildpack-python-opencv-scipy/tree/cedar14)) but was unsuccessful and ultimately stopped using heroku for hosting.

Take a look at the [dockerfile](https://github.com/diogojc/heroku-buildpack-python-opencv-scipy/blob/cedar14/Dockerfile) I've created to generate the binaries for cedar stack 14. 
If you can spot what I'm doing wrong you just need to change the URL in the buildpack to point to those new (working) binaries and submit a pull request.

**Comment by emschorsch** [comment]
do you mind updating the README to make that clear, I didn't think to look in the issues right away?

**Comment by Lucas63** [comment]
@emschorsch , hi i am trying to use solution presented on this post, but i doesnt work. Can you explain pls, how u use this solution?(from this url https://stackoverflow.com/questions/31270989/python-web-application-with-opencv-in-heroku)

**Comment by emschorsch** [comment]
@Lucas63 what have you tried so far? Have you tried doing it on their website? The ui is pretty reasonable I believe you just have to go to settings to find the adding buildpack options.

**Comment by Lucas63** [comment]
@emschorsch  i have tried a lot of different buildpacks...but its still doesnt working. I am trying this way : 
1) heroku buildpacks:add https://github.com/automata/heroku-buildpack-opencv --app billsaysapitest - add as additional buildpack( main is heroku/python)
2)And in other way i have tried : 
 heroku buildpacks:set https://github.com/automata/heroku-buildpack-opencv --app billsaysapitest - set as main buildpack. This buildpack shoud work on Stack : Cedar-14 or not?

**Comment by diogojc** [comment]
Hi guys.

I've updated the [](url)

**Comment by sarthaksharma058439** [comment]
Hey you can watch this video , in this video there is simplest way to install opencv with heroku 

https://youtu.be/9GCLwYlM8cc

I hope this will helps you , it fix my errors.
